"use client";

import { useState, useEffect, useCallback } from "react";
import { Highlight, themes } from "prism-react-renderer";
import katex from "katex";
import "katex/dist/katex.min.css";

interface ChatImageProps {
  src: string;
  alt: string;
}

const ChatImage = ({ src, alt }: ChatImageProps) => {
  const [copied, setCopied] = useState(false);
  const [hovered, setHovered] = useState(false);
  const [isFullscreen, setIsFullscreen] = useState(false);

  const handleDownload = (e?: React.MouseEvent) => {
    if (e) e.stopPropagation();
    const link = document.createElement("a");
    link.href = src;
    link.download = alt || "download.png";
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  const handleShare = (e?: React.MouseEvent) => {
    if (e) e.stopPropagation();
    const fullUrl = window.location.origin + src;
    if (navigator.share) {
      navigator.share({
        title: alt || "Generated Image",
        text: "Check out this image generated by Aarka AI!",
        url: fullUrl
      }).catch(console.error);
    } else {
      navigator.clipboard.writeText(fullUrl).then(() => {
        setCopied(true);
        setTimeout(() => setCopied(false), 2000);
      });
    }
  };

  useEffect(() => {
    if (isFullscreen) {
      const handleKeyDown = (e: KeyboardEvent) => {
        if (e.key === "Escape") setIsFullscreen(false);
      };
      window.addEventListener("keydown", handleKeyDown);
      document.body.style.overflow = "hidden";
      return () => {
        window.removeEventListener("keydown", handleKeyDown);
        document.body.style.overflow = "";
      };
    }
  }, [isFullscreen]);

  return (
    <div 
      className="cmark-image-container"
      style={{
        position: "relative",
        display: "inline-block",
        margin: "16px 0",
        maxWidth: "100%",
        borderRadius: "8px",
        overflow: "hidden"
      }}
      onMouseEnter={() => setHovered(true)}
      onMouseLeave={() => setHovered(false)}
    >
      <img 
        src={src} 
        alt={alt} 
        className="cmark-image" 
        onClick={() => setIsFullscreen(true)}
        style={{ 
          maxWidth: "100%", 
          height: "auto", 
          borderRadius: "8px", 
          display: "block",
          cursor: "zoom-in",
          transition: "transform 0.3s ease, filter 0.3s ease"
        }}
      />
      
      {/* Premium glassmorphism overlay on hover */}
      <div 
        style={{
          position: "absolute",
          top: "12px",
          right: "12px",
          display: "flex",
          gap: "8px",
          opacity: hovered ? 1 : 0,
          transition: "opacity 0.2s ease",
          background: "rgba(15, 23, 42, 0.6)",
          backdropFilter: "blur(4px)",
          padding: "6px",
          borderRadius: "8px",
          border: "1px solid rgba(255, 255, 255, 0.1)",
          boxShadow: "0 4px 12px rgba(0, 0, 0, 0.25)",
          zIndex: 10
        }}
      >
        {/* Download Button */}
        <button 
          onClick={handleDownload}
          style={{
            background: "none",
            border: "none",
            cursor: "pointer",
            padding: "6px",
            color: "#f8fafc",
            display: "flex",
            alignItems: "center",
            justifyContent: "center",
            borderRadius: "4px",
            transition: "all 0.2s ease"
          }}
          onMouseEnter={(e) => {
            e.currentTarget.style.background = "rgba(255, 255, 255, 0.15)";
            e.currentTarget.style.color = "#fbbf24";
          }}
          onMouseLeave={(e) => {
            e.currentTarget.style.background = "none";
            e.currentTarget.style.color = "#f8fafc";
          }}
          title="Download image"
        >
          <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round">
            <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4" />
            <polyline points="7 10 12 15 17 10" />
            <line x1="12" y1="15" x2="12" y2="3" />
          </svg>
        </button>

        {/* Share/Copy Button */}
        <button 
          onClick={handleShare}
          style={{
            background: "none",
            border: "none",
            cursor: "pointer",
            padding: "6px",
            color: "#f8fafc",
            display: "flex",
            alignItems: "center",
            justifyContent: "center",
            borderRadius: "4px",
            transition: "all 0.2s ease"
          }}
          onMouseEnter={(e) => {
            e.currentTarget.style.background = "rgba(255, 255, 255, 0.15)";
            e.currentTarget.style.color = "#fbbf24";
          }}
          onMouseLeave={(e) => {
            e.currentTarget.style.background = "none";
            e.currentTarget.style.color = "#f8fafc";
          }}
          title="Share image"
        >
          {copied ? (
            <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round">
              <polyline points="20 6 9 17 4 12" />
            </svg>
          ) : (
            <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round">
              <circle cx="18" cy="5" r="3" />
              <circle cx="6" cy="12" r="3" />
              <circle cx="18" cy="19" r="3" />
              <line x1="8.59" y1="13.51" x2="15.42" y2="17.49" />
              <line x1="15.41" y1="6.51" x2="8.59" y2="10.49" />
            </svg>
          )}
        </button>
      </div>

      {/* Copied toast overlay */}
      {copied && (
        <div 
          style={{
            position: "absolute",
            bottom: "12px",
            left: "50%",
            transform: "translateX(-50%)",
            background: "rgba(15, 23, 42, 0.8)",
            color: "#fbbf24",
            padding: "6px 12px",
            borderRadius: "6px",
            fontSize: "11px",
            fontWeight: 600,
            pointerEvents: "none",
            zIndex: 15
          }}
        >
          Link copied!
        </div>
      )}

      {/* Fullscreen Lightbox Modal */}
      {isFullscreen && (
        <div 
          onClick={() => setIsFullscreen(false)}
          style={{
            position: "fixed",
            top: 0,
            left: 0,
            width: "100vw",
            height: "100vh",
            background: "rgba(9, 15, 29, 0.92)",
            backdropFilter: "blur(12px)",
            zIndex: 99999,
            display: "flex",
            alignItems: "center",
            justifyContent: "center",
            cursor: "zoom-out"
          }}
        >
          {/* Top bar with image details and actions */}
          <div 
            style={{
              position: "absolute",
              top: 0,
              left: 0,
              width: "100%",
              padding: "20px 30px",
              display: "flex",
              justifyContent: "space-between",
              alignItems: "center",
              background: "linear-gradient(to bottom, rgba(0,0,0,0.85), transparent)",
              color: "#f8fafc"
            }}
            onClick={(e) => e.stopPropagation()}
          >
            <span style={{ fontSize: "14px", fontWeight: 500, fontFamily: "Inter, sans-serif" }}>
              {alt || "Generated Image"}
            </span>
            
            <div style={{ display: "flex", gap: "12px", alignItems: "center" }}>
              {/* Download */}
              <button 
                onClick={handleDownload}
                style={{
                  background: "rgba(255,255,255,0.1)",
                  border: "none",
                  cursor: "pointer",
                  padding: "8px 14px",
                  color: "#f8fafc",
                  borderRadius: "6px",
                  display: "flex",
                  alignItems: "center",
                  gap: "6px",
                  fontSize: "13px",
                  fontWeight: 500,
                  transition: "all 0.2s"
                }}
                onMouseEnter={(e) => e.currentTarget.style.background = "rgba(255,255,255,0.2)"}
                onMouseLeave={(e) => e.currentTarget.style.background = "rgba(255,255,255,0.1)"}
              >
                <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5">
                  <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4" />
                  <polyline points="7 10 12 15 17 10" />
                  <line x1="12" y1="15" x2="12" y2="3" />
                </svg>
                <span>Download</span>
              </button>
              
              {/* Share */}
              <button 
                onClick={handleShare}
                style={{
                  background: "rgba(255,255,255,0.1)",
                  border: "none",
                  cursor: "pointer",
                  padding: "8px 14px",
                  color: "#f8fafc",
                  borderRadius: "6px",
                  display: "flex",
                  alignItems: "center",
                  gap: "6px",
                  fontSize: "13px",
                  fontWeight: 500,
                  transition: "all 0.2s"
                }}
                onMouseEnter={(e) => e.currentTarget.style.background = "rgba(255,255,255,0.2)"}
                onMouseLeave={(e) => e.currentTarget.style.background = "rgba(255,255,255,0.1)"}
              >
                {copied ? (
                  <>
                    <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5">
                      <polyline points="20 6 9 17 4 12" />
                    </svg>
                    <span>Copied!</span>
                  </>
                ) : (
                  <>
                    <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5">
                      <circle cx="18" cy="5" r="3" />
                      <circle cx="6" cy="12" r="3" />
                      <circle cx="18" cy="19" r="3" />
                      <line x1="8.59" y1="13.51" x2="15.42" y2="17.49" />
                      <line x1="15.41" y1="6.51" x2="8.59" y2="10.49" />
                    </svg>
                    <span>Share</span>
                  </>
                )}
              </button>

              {/* Close */}
              <button 
                onClick={() => setIsFullscreen(false)}
                style={{
                  background: "rgba(239, 68, 68, 0.2)",
                  border: "none",
                  cursor: "pointer",
                  padding: "8px",
                  color: "#ef4444",
                  borderRadius: "6px",
                  display: "flex",
                  alignItems: "center",
                  justifyContent: "center",
                  transition: "all 0.2s"
                }}
                onMouseEnter={(e) => e.currentTarget.style.background = "rgba(239, 68, 68, 0.3)"}
                onMouseLeave={(e) => e.currentTarget.style.background = "rgba(239, 68, 68, 0.2)"}
                title="Close fullscreen"
              >
                <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5">
                  <line x1="18" y1="6" x2="6" y2="18" />
                  <line x1="6" y1="6" x2="18" y2="18" />
                </svg>
              </button>
            </div>
          </div>

          {/* Centered Image */}
          <img 
            src={src} 
            alt={alt} 
            style={{
              width: "100%",
              height: "100%",
              maxWidth: "90vw",
              maxHeight: "80vh",
              borderRadius: "6px",
              boxShadow: "0 24px 50px rgba(0,0,0,0.6)",
              objectFit: "contain",
              cursor: "default"
            }}
            onClick={(e) => e.stopPropagation()}
          />
        </div>
      )}
    </div>
  );
};

interface ChatMarkdownProps {
  content: string;
  isStreaming?: boolean;
}

const ChatMarkdown = ({ content, isStreaming }: ChatMarkdownProps) => {
  const [copiedBlock, setCopiedBlock] = useState<number | null>(null);

  const copyCode = useCallback((code: string, index: number) => {
    navigator.clipboard.writeText(code).then(() => {
      setCopiedBlock(index);
      setTimeout(() => setCopiedBlock(null), 2000);
    });
  }, []);

  const renderContent = () => {
    // Split by code blocks first
    // Handle \r\n and any trailing whitespace after the language identifier
    const codeBlockRegex = /```([a-zA-Z0-9_+-]*)[^\n]*\n([\s\S]*?)```/g;
    const parts: { type: "text" | "code"; content: string; lang?: string }[] = [];
    let lastIndex = 0;
    let match;
    let blockIndex = 0;

    while ((match = codeBlockRegex.exec(content)) !== null) {
      if (match.index > lastIndex) {
        parts.push({ type: "text", content: content.slice(lastIndex, match.index) });
      }
      parts.push({ type: "code", content: match[2], lang: match[1] || "text" });
      lastIndex = match.index + match[0].length;
    }
    if (lastIndex < content.length) {
      parts.push({ type: "text", content: content.slice(lastIndex) });
    }

    return parts.map((part, i) => {
      const isLastPart = i === parts.length - 1;
      if (part.type === "code") {
        const idx = blockIndex++;
        const code = (isLastPart && isStreaming) ? part.content : part.content.trimEnd();
        const lang = part.lang || "text";
        return (
          <div key={i} className="cmark-codeblock">
            <div className="cmark-codeblock-header">
              <span className="cmark-codeblock-lang">{lang}</span>
              <button
                className="cmark-copy-btn"
                onClick={() => copyCode(code, idx)}
              >
                {copiedBlock === idx ? (
                  <>
                    <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><polyline points="20 6 9 17 4 12"/></svg>
                    <span>Copied!</span>
                  </>
                ) : (
                  <>
                    <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 01-2-2V4a2 2 0 012-2h9a2 2 0 012 2v1"/></svg>
                    <span>Copy</span>
                  </>
                )}
              </button>
            </div>
            <Highlight
              theme={themes.nightOwl}
              code={code}
              language={lang}
            >
              {({ style, tokens, getLineProps, getTokenProps }) => (
                <pre className="cmark-pre" style={{ ...style, background: "transparent", margin: 0 }}>
                  {tokens.map((line, lineIdx) => (
                    <div key={lineIdx} {...getLineProps({ line })}>
                      {line.map((token, tokenIdx) => (
                        <span key={tokenIdx} {...getTokenProps({ token })} />
                      ))}
                      {isLastPart && lineIdx === tokens.length - 1 && isStreaming && <span className="cmark-cursor" />}
                    </div>
                  ))}
                </pre>
              )}
            </Highlight>
          </div>
        );
      }

      return <span key={i}>{renderInlineMarkdown(part.content, isLastPart)}</span>;
    });
  };

  /**
   * Merge consecutive paragraphs that are each a single ordered-list item
   * (e.g. "1. Foo", "2. Bar") into one combined paragraph so the ordered
   * list renderer can produce a single <ol> with correct numbering.
   */
  const mergeParagraphs = (paragraphs: string[], isStreamingActive: boolean): string[] => {
    const merged: string[] = [];
    for (let i = 0; i < paragraphs.length; i++) {
      const para = paragraphs[i];
      const isLast = i === paragraphs.length - 1;
      const trimmed = para.trim();
      if (!trimmed && !(isLast && isStreamingActive)) continue;
      const lines = trimmed.split("\n");
      const isSingleOl =
        trimmed && lines.length === 1 && /^\s*\d+[.)]\s/.test(lines[0]);
      // Also handle multi-line list items where continuation lines are indented
      const isMultiLineOlItem =
        trimmed && lines.length > 1 &&
        /^\s*\d+[.)]\s/.test(lines[0]) &&
        lines.slice(1).every((l) => /^\s{2,}/.test(l) || l.trim() === "");
      if (
        (isSingleOl || isMultiLineOlItem) &&
        merged.length > 0
      ) {
        const prev = merged[merged.length - 1];
        const prevTrimmed = prev.trim();
        const prevLines = prevTrimmed.split("\n");
        const prevIsOl = prevLines.every(
          (l) => /^\s*\d+[.)]\s/.test(l) || /^\s{2,}/.test(l) || l.trim() === ""
        ) && /^\s*\d+[.)]\s/.test(prevLines[0]);
        if (prevIsOl) {
          merged[merged.length - 1] = prev + "\n" + para;
          continue;
        }
      }
      merged.push(para);
    }
    return merged;
  };

  const renderInlineMarkdown = (text: string, isLastPart: boolean) => {
    // Split into paragraphs, then merge consecutive ordered-list items
    const rawParagraphs = text.split(/\n\n+/);
    const paragraphs = mergeParagraphs(rawParagraphs, !!isStreaming && isLastPart);

    return paragraphs.map((para, pIdx) => {
      const trimmed = para.trim();
      const isLastPara = isLastPart && pIdx === paragraphs.length - 1;

      if (!trimmed) {
        if (isLastPara && isStreaming) {
          const lines = para.split("\n");
          return (
            <p key={pIdx} className="cmark-p">
              {lines.map((line, li) => {
                const isLastLine = li === lines.length - 1;
                return (
                  <span key={li}>
                    {li > 0 && <br />}
                    {line}
                    {isLastLine && <span className="cmark-cursor" />}
                  </span>
                );
              })}
            </p>
          );
        }
        return null;
      }

      // Check for blockquote
      if (trimmed.startsWith("> ")) {
        const lines = para.split("\n");
        const quoteContent = lines
          .map((l) => l.replace(/^\s*>\s?/, ""))
          .join("\n");
        return (
          <blockquote key={pIdx} className="cmark-blockquote">
            {renderInline(quoteContent)}
            {isLastPara && isStreaming && <span className="cmark-cursor" />}
          </blockquote>
        );
      }

      // Check for unordered list
      const ulLines = trimmed.split("\n");
      if (ulLines.every((l) => /^\s*[-*]\s/.test(l) || l.trim() === "")) {
        const originalLines = para.split("\n");
        const filteredLines = originalLines.filter((l, li) => {
          const isLastLine = isLastPara && li === originalLines.length - 1;
          return l.trim() || (isLastLine && isStreaming);
        });
        return (
          <ul key={pIdx} className="cmark-ul">
            {filteredLines.map((l, li) => {
              const isLastItem = isLastPara && li === filteredLines.length - 1;
              const cleanedLine = l.replace(/^\s*[-*]\s/, "");
              return (
                <li key={li}>
                  {renderInline(cleanedLine)}
                  {isLastItem && isStreaming && <span className="cmark-cursor" />}
                </li>
              );
            })}
          </ul>
        );
      }

      // Check for ordered list
      if (ulLines.every((l) => /^\s*\d+[.)]\s/.test(l) || l.trim() === "")) {
        const originalLines = para.split("\n");
        const filteredLines = originalLines.filter((l, li) => {
          const isLastLine = isLastPara && li === originalLines.length - 1;
          return l.trim() || (isLastLine && isStreaming);
        });
        return (
          <ol key={pIdx} className="cmark-ol">
            {filteredLines.map((l, li) => {
              const isLastItem = isLastPara && li === filteredLines.length - 1;
              const cleanedLine = l.replace(/^\s*\d+[.)]\s/, "");
              return (
                <li key={li}>
                  {renderInline(cleanedLine)}
                  {isLastItem && isStreaming && <span className="cmark-cursor" />}
                </li>
              );
            })}
          </ol>
        );
      }

      // Check for heading
      const headingMatch = trimmed.match(/^(#{1,3})\s+(.+)$/);
      if (headingMatch) {
        const level = headingMatch[1].length;
        const Tag = `h${level + 2}` as "h3" | "h4" | "h5";
        const marker = headingMatch[1];
        const headingContent = para.replace(new RegExp(`^\\s*${marker}\\s*`), "");
        return (
          <Tag key={pIdx} className="cmark-heading">
            {renderInline(headingContent)}
            {isLastPara && isStreaming && <span className="cmark-cursor" />}
          </Tag>
        );
      }

      // Regular paragraph — handle single newlines as <br/>
      const lines = para.split("\n");
      return (
        <p key={pIdx} className="cmark-p">
          {lines.map((line, li) => {
            const isLastLine = isLastPara && li === lines.length - 1;
            return (
              <span key={li}>
                {li > 0 && <br />}
                {renderInline(line)}
                {isLastLine && isStreaming && <span className="cmark-cursor" />}
              </span>
            );
          })}
        </p>
      );
    });
  };

  const renderInline = (text: string): React.ReactNode[] => {
    // Process inline markdown: images, bold, italic, inline code, links, block/inline LaTeX math
    const tokens: React.ReactNode[] = [];
    const regex = /(!\[(.+?)\]\((.+?)\))|(\*\*(.+?)\*\*)|(\*(.+?)\*)|(`(.+?)`)|\[(.+?)\]\((.+?)\)|(\\?\$\$[\s\S]*?\$\$)|(\\?\$[^$]+?\$)|(\\\[[\s\S]*?\\\])|(\\?\([\s\S]*?\\\))/g;
    let lastIdx = 0;
    let m;

    while ((m = regex.exec(text)) !== null) {
      if (m.index > lastIdx) {
        tokens.push(text.slice(lastIdx, m.index));
      }

      if (m[1]) {
        // Image ![alt](url)
        tokens.push(
          <ChatImage 
            key={m.index} 
            src={m[3]} 
            alt={m[2]} 
          />
        );
      } else if (m[4]) {
        // Bold
        tokens.push(<strong key={m.index}>{m[5]}</strong>);
      } else if (m[6]) {
        // Italic
        tokens.push(<em key={m.index}>{m[7]}</em>);
      } else if (m[8]) {
        // Inline code
        tokens.push(<code key={m.index} className="cmark-inline-code">{m[9]}</code>);
      } else if (m[10]) {
        // Link
        tokens.push(
          <a key={m.index} href={m[11]} target="_blank" rel="noopener noreferrer" className="cmark-link">
            {m[10]}
            <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" style={{ display: "inline", marginLeft: 2, verticalAlign: "middle" }}>
              <path d="M18 13v6a2 2 0 01-2 2H5a2 2 0 01-2-2V8a2 2 0 012-2h6" />
              <polyline points="15 3 21 3 21 9" />
              <line x1="10" y1="14" x2="21" y2="3" />
            </svg>
          </a>
        );
      } else if (m[13]) {
        // Block LaTeX math $$ ... $$ or \[ ... \]
        const mathContent = m[13].replace(/^\$\$|\$\$$/g, "").replace(/^\\\[|\\\]$/g, "").trim();
        try {
          const html = katex.renderToString(mathContent, { displayMode: true, throwOnError: false });
          tokens.push(
            <span
              key={m.index}
              className="cmark-block-math"
              dangerouslySetInnerHTML={{ __html: html }}
            />
          );
        } catch (err) {
          console.error("KaTeX block render error:", err);
          tokens.push(<span key={m.index} style={{ color: "#ef4444" }}>{m[13]}</span>);
        }
      } else if (m[14]) {
        // Inline LaTeX math $ ... $ or \( ... \)
        const mathContent = m[14].replace(/^\$|\$$/g, "").replace(/^\\\(|\\\)$/g, "").trim();
        try {
          const html = katex.renderToString(mathContent, { displayMode: false, throwOnError: false });
          tokens.push(
            <span
              key={m.index}
              className="cmark-inline-math"
              dangerouslySetInnerHTML={{ __html: html }}
            />
          );
        } catch (err) {
          console.error("KaTeX inline render error:", err);
          tokens.push(<span key={m.index} style={{ color: "#ef4444" }}>{m[14]}</span>);
        }
      } else if (m[15]) {
        // Block LaTeX \[ ... \]
        const mathContent = m[15].replace(/^\\\[|\\\]$/g, "").trim();
        try {
          const html = katex.renderToString(mathContent, { displayMode: true, throwOnError: false });
          tokens.push(
            <span key={m.index} className="cmark-block-math" dangerouslySetInnerHTML={{ __html: html }} />
          );
        } catch (err) {
          console.error("KaTeX block render error:", err);
          tokens.push(<span key={m.index} style={{ color: "#ef4444" }}>{m[15]}</span>);
        }
      } else if (m[16]) {
        // Inline LaTeX \( ... \)
        const mathContent = m[16].replace(/^\\\(|\\\)$/g, "").trim();
        try {
          const html = katex.renderToString(mathContent, { displayMode: false, throwOnError: false });
          tokens.push(
            <span key={m.index} className="cmark-inline-math" dangerouslySetInnerHTML={{ __html: html }} />
          );
        } catch (err) {
          console.error("KaTeX inline render error:", err);
          tokens.push(<span key={m.index} style={{ color: "#ef4444" }}>{m[16]}</span>);
        }
      }

      lastIdx = m.index + m[0].length;
    }

    if (lastIdx < text.length) {
      tokens.push(text.slice(lastIdx));
    }

    return tokens;
  };

  return (
    <div className="cmark-root">
      {renderContent()}
    </div>
  );
};

export default ChatMarkdown;
